import json
import os

##
## INSTRUCTIONS: FIRST ADD POST TO POSTS.JSON
## THEN RUN THIS TO CREATE TEMPLATE
## THEN EDIT THE POST TEMPLATE HTML
## 

# Directory where the posts are stored
post_dir = 'posts/'

# Load posts from JSON
with open('posts.json', 'r') as file:
    posts = json.load(file)


# Load the HTML template
with open('post_template.html', 'r') as template_file:
    template = template_file.read()

# List all current posts in the directory
current_posts = os.listdir(post_dir)

# Track whether all posts are synced
all_synced = True

# Check each post from JSON
for post in posts:
    filename = post['filename']

    # If the post doesn't exist, create it
    if filename not in current_posts:
        with open(post_dir + filename, 'w') as file:
            file.write(f"<!--\nAutogenerated comment from sync_posts.py\nTitle: {post['title']}\nDate: {post['date']}\nDescription: {post['description']}\n-->\n")
            file.write(template)
            print(f'Created file {filename}')
        all_synced = False
    else:
        current_posts.remove(filename)

# Check for untracked posts
if current_posts:
    print('Error: untracked files')
    for post in current_posts:
        print(post)
    all_synced = False

# If all posts are synced
if all_synced:
    print('OK: All posts synced')
